export const places = [
  {
    id: "place_1",
    name: "Fort Aguada",
    city: "Goa",
    category: "sightseeing",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_1/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 90,
    tags: ["history", "sunset", "fort"],
  },
  {
    id: "place_2",
    name: "Basilica of Bom Jesus",
    city: "Goa",
    category: "sightseeing",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/place_2/400/300",
    priceLevel: "low",
    closingTime: "18:30",
    averageVisitTime: 60,
    tags: ["history", "heritage", "church"],
  },
  {
    id: "place_3",
    name: "Se Cathedral",
    city: "Goa",
    category: "sightseeing",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/place_3/400/300",
    priceLevel: "low",
    closingTime: "18:30",
    averageVisitTime: 45,
    tags: ["history", "heritage", "church"],
  },
  {
    id: "place_4",
    name: "Dudhsagar Falls",
    city: "Goa",
    category: "sightseeing",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/place_4/400/300",
    priceLevel: "medium",
    closingTime: "17:00",
    averageVisitTime: 180,
    tags: ["waterfall", "nature", "trek"],
  },
  {
    id: "place_5",
    name: "Chapora Fort",
    city: "Goa",
    category: "sightseeing",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_5/400/300",
    priceLevel: "low",
    closingTime: "17:30",
    averageVisitTime: 75,
    tags: ["fort", "sunset", "viewpoint"],
  },
  {
    id: "place_6",
    name: "Palolem Beach",
    city: "Goa",
    category: "sightseeing",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/place_6/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 120,
    tags: ["beach", "sunset", "relax"],
  },
  {
    id: "place_7",
    name: "Calangute Beach",
    city: "Goa",
    category: "sightseeing",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_7/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 90,
    tags: ["beach", "water-sports", "popular"],
  },
  {
    id: "place_8",
    name: "Baga Beach",
    city: "Goa",
    category: "sightseeing",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_8/400/300",
    priceLevel: "medium",
    closingTime: "18:00",
    averageVisitTime: 90,
    tags: ["beach", "water-sports", "popular"],
  },
  {
    id: "place_9",
    name: "Old Goa Heritage Walk",
    city: "Goa",
    category: "sightseeing",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_9/400/300",
    priceLevel: "low",
    closingTime: "17:00",
    averageVisitTime: 120,
    tags: ["history", "heritage", "walking-tour"],
  },
  {
    id: "place_10",
    name: "Spice Plantation Tour",
    city: "Goa",
    category: "sightseeing",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_10/400/300",
    priceLevel: "medium",
    closingTime: "17:00",
    averageVisitTime: 150,
    tags: ["nature", "food", "guided-tour"],
  },
  {
    id: "place_11",
    name: "Aguada Lighthouse",
    city: "Goa",
    category: "sightseeing",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_11/400/300",
    priceLevel: "low",
    closingTime: "17:30",
    averageVisitTime: 45,
    tags: ["history", "viewpoint", "fort"],
  },
  {
    id: "place_12",
    name: "Dona Paula Viewpoint",
    city: "Goa",
    category: "sightseeing",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_12/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 60,
    tags: ["viewpoint", "sunset", "coastal"],
  },
  {
    id: "place_13",
    name: "Cotigao Wildlife Sanctuary",
    city: "Goa",
    category: "sightseeing",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_13/400/300",
    priceLevel: "medium",
    closingTime: "17:00",
    averageVisitTime: 120,
    tags: ["nature", "wildlife", "forest"],
  },
  {
    id: "place_14",
    name: "Tambdi Surla Temple",
    city: "Goa",
    category: "sightseeing",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_14/400/300",
    priceLevel: "low",
    closingTime: "17:30",
    averageVisitTime: 60,
    tags: ["heritage", "temple", "history"],
  },
  {
    id: "place_15",
    name: "Mangeshi Temple",
    city: "Goa",
    category: "sightseeing",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_15/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 45,
    tags: ["heritage", "temple", "culture"],
  },
  {
    id: "place_16",
    name: "Salim Ali Bird Sanctuary",
    city: "Goa",
    category: "sightseeing",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_16/400/300",
    priceLevel: "medium",
    closingTime: "17:00",
    averageVisitTime: 90,
    tags: ["nature", "wildlife", "birds"],
  },
  {
    id: "place_17",
    name: "Reis Magos Fort",
    city: "Goa",
    category: "sightseeing",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_17/400/300",
    priceLevel: "low",
    closingTime: "17:30",
    averageVisitTime: 75,
    tags: ["fort", "history", "river-view"],
  },
  {
    id: "place_18",
    name: "Arambol Sweet Lake",
    city: "Goa",
    category: "sightseeing",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_18/400/300",
    priceLevel: "low",
    closingTime: "18:00",
    averageVisitTime: 90,
    tags: ["nature", "lake", "relax"],
  },
  {
    id: "place_19",
    name: "Cabo de Rama Fort",
    city: "Goa",
    category: "sightseeing",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_19/400/300",
    priceLevel: "low",
    closingTime: "17:30",
    averageVisitTime: 90,
    tags: ["fort", "history", "viewpoint"],
  },
  {
    id: "place_20",
    name: "Gunpowder",
    city: "Goa",
    category: "food",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/place_20/400/300",
    priceLevel: "high",
    closingTime: "22:30",
    averageVisitTime: 90,
    tags: ["goan", "seafood", "fine-dining"],
  },
  {
    id: "place_21",
    name: "Britto's Beach Shack",
    city: "Goa",
    category: "food",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_21/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 75,
    tags: ["seafood", "beach", "goan"],
  },
  {
    id: "place_22",
    name: "Martin's Corner",
    city: "Goa",
    category: "food",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_22/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 90,
    tags: ["goan", "family", "popular"],
  },
  {
    id: "place_23",
    name: "Vinayak Family Restaurant",
    city: "Goa",
    category: "food",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_23/400/300",
    priceLevel: "low",
    closingTime: "22:00",
    averageVisitTime: 60,
    tags: ["goan", "thali", "budget"],
  },
  {
    id: "place_24",
    name: "Fisherman's Wharf",
    city: "Goa",
    category: "food",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_24/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 90,
    tags: ["seafood", "riverside", "goan"],
  },
  {
    id: "place_25",
    name: "Souza Lobo",
    city: "Goa",
    category: "food",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_25/400/300",
    priceLevel: "medium",
    closingTime: "22:30",
    averageVisitTime: 75,
    tags: ["seafood", "beach", "heritage"],
  },
  {
    id: "place_26",
    name: "Vinayak Restaurant Mapusa",
    city: "Goa",
    category: "food",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_26/400/300",
    priceLevel: "low",
    closingTime: "22:00",
    averageVisitTime: 60,
    tags: ["goan", "budget", "local"],
  },
  {
    id: "place_27",
    name: "Bhaji Pao",
    city: "Goa",
    category: "food",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_27/400/300",
    priceLevel: "low",
    closingTime: "21:30",
    averageVisitTime: 45,
    tags: ["street-food", "budget", "local"],
  },
  {
    id: "place_28",
    name: "Pousada By The Beach",
    city: "Goa",
    category: "food",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/place_28/400/300",
    priceLevel: "high",
    closingTime: "23:00",
    averageVisitTime: 90,
    tags: ["seafood", "fine-dining", "beach"],
  },
  {
    id: "place_29",
    name: "Ritz Classic",
    city: "Goa",
    category: "food",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_29/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 75,
    tags: ["goan", "seafood", "popular"],
  },
  {
    id: "place_30",
    name: "Zeebop by the Sea",
    city: "Goa",
    category: "food",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_30/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 75,
    tags: ["seafood", "beach", "sunset"],
  },
  {
    id: "place_31",
    name: "Mum's Kitchen",
    city: "Goa",
    category: "food",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/place_31/400/300",
    priceLevel: "high",
    closingTime: "22:30",
    averageVisitTime: 90,
    tags: ["goan", "heritage", "fine-dining"],
  },
  {
    id: "place_32",
    name: "Noronha's Corner",
    city: "Goa",
    category: "food",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_32/400/300",
    priceLevel: "low",
    closingTime: "22:00",
    averageVisitTime: 60,
    tags: ["goan", "budget", "local"],
  },
  {
    id: "place_33",
    name: "Joseph Bar",
    city: "Goa",
    category: "food",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_33/400/300",
    priceLevel: "low",
    closingTime: "22:30",
    averageVisitTime: 60,
    tags: ["bar", "local", "budget"],
  },
  {
    id: "place_34",
    name: "Zomway Shack",
    city: "Goa",
    category: "food",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_34/400/300",
    priceLevel: "low",
    closingTime: "22:00",
    averageVisitTime: 45,
    tags: ["beach", "budget", "casual"],
  },
  {
    id: "place_35",
    name: "The Black Sheep Bistro",
    city: "Goa",
    category: "food",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_35/400/300",
    priceLevel: "high",
    closingTime: "23:00",
    averageVisitTime: 90,
    tags: ["fusion", "fine-dining", "popular"],
  },
  {
    id: "place_36",
    name: "Saraya Eco Stay Cafe",
    city: "Goa",
    category: "food",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_36/400/300",
    priceLevel: "medium",
    closingTime: "22:00",
    averageVisitTime: 75,
    tags: ["organic", "cafe", "relax"],
  },
  {
    id: "place_37",
    name: "Fernando's Nostalgia",
    city: "Goa",
    category: "food",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/place_37/400/300",
    priceLevel: "high",
    closingTime: "22:30",
    averageVisitTime: 90,
    tags: ["portuguese", "heritage", "fine-dining"],
  },
  {
    id: "place_38",
    name: "Anjuna Flea Market",
    city: "Goa",
    category: "shopping",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_38/400/300",
    priceLevel: "low",
    closingTime: "19:00",
    averageVisitTime: 120,
    tags: ["flea-market", "souvenirs", "handicrafts"],
  },
  {
    id: "place_39",
    name: "Mapusa Market",
    city: "Goa",
    category: "shopping",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_39/400/300",
    priceLevel: "low",
    closingTime: "20:00",
    averageVisitTime: 90,
    tags: ["local-market", "spices", "budget"],
  },
  {
    id: "place_40",
    name: "Mall De Goa",
    city: "Goa",
    category: "shopping",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_40/400/300",
    priceLevel: "medium",
    closingTime: "22:00",
    averageVisitTime: 120,
    tags: ["mall", "brands", "indoor"],
  },
  {
    id: "place_41",
    name: "Saturday Night Market Arpora",
    city: "Goa",
    category: "shopping",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_41/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 150,
    tags: ["night-market", "handicrafts", "live-music"],
  },
  {
    id: "place_42",
    name: "Calangute Market Square",
    city: "Goa",
    category: "shopping",
    rating: 3.9,
    imageUrl: "https://picsum.photos/seed/place_42/400/300",
    priceLevel: "low",
    closingTime: "20:00",
    averageVisitTime: 90,
    tags: ["local-market", "souvenirs", "budget"],
  },
  {
    id: "place_43",
    name: "Mackie's Night Bazaar",
    city: "Goa",
    category: "shopping",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_43/400/300",
    priceLevel: "medium",
    closingTime: "23:00",
    averageVisitTime: 120,
    tags: ["night-market", "handicrafts", "food-stalls"],
  },
  {
    id: "place_44",
    name: "Candolim Main Market",
    city: "Goa",
    category: "shopping",
    rating: 3.8,
    imageUrl: "https://picsum.photos/seed/place_44/400/300",
    priceLevel: "low",
    closingTime: "20:00",
    averageVisitTime: 60,
    tags: ["local-market", "budget", "daily-needs"],
  },
  {
    id: "place_45",
    name: "Fontainhas Heritage Shop",
    city: "Goa",
    category: "shopping",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_45/400/300",
    priceLevel: "medium",
    closingTime: "19:00",
    averageVisitTime: 60,
    tags: ["heritage", "handicrafts", "souvenirs"],
  },
  {
    id: "place_46",
    name: "Tibetan Market Baga",
    city: "Goa",
    category: "shopping",
    rating: 3.9,
    imageUrl: "https://picsum.photos/seed/place_46/400/300",
    priceLevel: "low",
    closingTime: "20:00",
    averageVisitTime: 75,
    tags: ["street-market", "clothes", "budget"],
  },
  {
    id: "place_47",
    name: "Goa Handicrafts Emporium",
    city: "Goa",
    category: "shopping",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_47/400/300",
    priceLevel: "medium",
    closingTime: "19:30",
    averageVisitTime: 60,
    tags: ["handicrafts", "souvenirs", "government"],
  },
  {
    id: "place_48",
    name: "Azad Gali Shopping Lane",
    city: "Goa",
    category: "shopping",
    rating: 3.8,
    imageUrl: "https://picsum.photos/seed/place_48/400/300",
    priceLevel: "low",
    closingTime: "20:00",
    averageVisitTime: 75,
    tags: ["street-shopping", "clothes", "budget"],
  },
  {
    id: "place_49",
    name: "Caculo Mall",
    city: "Goa",
    category: "shopping",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_49/400/300",
    priceLevel: "medium",
    closingTime: "22:00",
    averageVisitTime: 90,
    tags: ["mall", "brands", "indoor"],
  },
  {
    id: "place_50",
    name: "Tito's Lane",
    city: "Goa",
    category: "nightlife",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_50/400/300",
    priceLevel: "high",
    closingTime: "03:00",
    averageVisitTime: 180,
    tags: ["club", "dance", "popular"],
  },
  {
    id: "place_51",
    name: "Curlies Beach Shack",
    city: "Goa",
    category: "nightlife",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/place_51/400/300",
    priceLevel: "medium",
    closingTime: "02:00",
    averageVisitTime: 150,
    tags: ["beach", "live-music", "sunset"],
  },
  {
    id: "place_52",
    name: "Shiva Valley",
    city: "Goa",
    category: "nightlife",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_52/400/300",
    priceLevel: "low",
    closingTime: "02:00",
    averageVisitTime: 120,
    tags: ["trance", "beach", "budget"],
  },
  {
    id: "place_53",
    name: "Cafe Mambos",
    city: "Goa",
    category: "nightlife",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_53/400/300",
    priceLevel: "high",
    closingTime: "03:00",
    averageVisitTime: 150,
    tags: ["club", "dance", "popular"],
  },
  {
    id: "place_54",
    name: "SinQ Nightclub",
    city: "Goa",
    category: "nightlife",
    rating: 4.1,
    imageUrl: "https://picsum.photos/seed/place_54/400/300",
    priceLevel: "high",
    closingTime: "03:00",
    averageVisitTime: 180,
    tags: ["club", "dance", "premium"],
  },
  {
    id: "place_55",
    name: "Club Cubana",
    city: "Goa",
    category: "nightlife",
    rating: 4.2,
    imageUrl: "https://picsum.photos/seed/place_55/400/300",
    priceLevel: "high",
    closingTime: "03:00",
    averageVisitTime: 180,
    tags: ["club", "pool-party", "premium"],
  },
  {
    id: "place_56",
    name: "LPK Waterfront",
    city: "Goa",
    category: "nightlife",
    rating: 4.0,
    imageUrl: "https://picsum.photos/seed/place_56/400/300",
    priceLevel: "medium",
    closingTime: "02:30",
    averageVisitTime: 150,
    tags: ["club", "riverside", "dance"],
  },
  {
    id: "place_57",
    name: "Hammerzz Nightclub",
    city: "Goa",
    category: "nightlife",
    rating: 3.9,
    imageUrl: "https://picsum.photos/seed/place_57/400/300",
    priceLevel: "medium",
    closingTime: "02:30",
    averageVisitTime: 150,
    tags: ["club", "dance", "popular"],
  },
  {
    id: "place_58",
    name: "Club Zephyr",
    city: "Goa",
    category: "nightlife",
    rating: 3.8,
    imageUrl: "https://picsum.photos/seed/place_58/400/300",
    priceLevel: "medium",
    closingTime: "02:00",
    averageVisitTime: 120,
    tags: ["club", "beach", "dance"],
  },
  {
    id: "place_59",
    name: "Silent Noise Party Palolem",
    city: "Goa",
    category: "nightlife",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/place_59/400/300",
    priceLevel: "medium",
    closingTime: "01:00",
    averageVisitTime: 150,
    tags: ["headphones", "beach", "unique"],
  },
  {
    id: "place_60",
    name: "Hilltop Vagator",
    city: "Goa",
    category: "nightlife",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/place_60/400/300",
    priceLevel: "medium",
    closingTime: "02:00",
    averageVisitTime: 150,
    tags: ["sunset", "trance", "viewpoint"],
  },
];
